MiniFilRouge/Models/MesCommandes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MiniFilRouge.Models
{
    public class MesCommandes
    {
        public int UserAccountId { get; set; }

        public string NomClient { get; set; }
        public string PrenomClient { get; set; }

        public string NomProduit { get; set; }
        public int Quantite { get; set; }

        public int PrixTotal { get; set; }
    }
}

MiniFilRouge/Controllers/UserAccountController.cs
using MiniFilRouge.Metier;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniFilRouge.Controllers
{
    public class UserAccountController : Controller
    {
        public IUserAccount Iuser = new UserAccountImpl();
        public IProduit Iprod = new ProduitImpl();
        // GET: UserAccount
        public ActionResult Index()
        {
            return View(Iuser.findAllUser());
        }
        public ActionResult Register()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult Register(UserAccount userAccount )
        {
            if (ModelState.IsValid)
            {
                Iuser.AddUserAccount(userAccount);
                ModelState.Clear();
                ViewBag.Message = userAccount.FirstName+ " "+ userAccount.LastName+ " enregistré";
            }
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(UserAccount userAccount)
        {
         
            var monUser = Iuser.LoginUser(userAccount);
            if (monUser != null)
            {
                Session["UserId"] = monUser.UserAccountId;
                Session["Username"] = monUser.Username;
                Session["user"] = monUser;
                return RedirectToAction("LoggedIn");
               // ViewBag.Message = "Bonjour " + monUser.FirstName + " " + monUser.LastName;
            }
            else
            {
                ModelState.AddModelError("", "utilisateur ou mot de passe incorrect");
            }
            return View();
        }
        public ActionResult LoggedIn()
        {
            if (Session["UserId"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        public ActionResult Logout()
        {
            Session["UserId"] = null;
            Session["Username"] = null;
            Session["user"] = null;
            return RedirectToAction("Login");
        }

        public ActionResult Commander()
        {

            return View(Iprod.findAllProduits());
        }

        [HttpPost]
        public ActionResult Commander(Commande c)
        {
            Panier p = new Panier();

            return View();
        }
        private int isExisting(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for(int i = 0; i < cart.Count; i++)
                if (cart[i].Pr.ProduitId == id)
                    return i;
                return -1;
        }

        public ActionResult Delete(int id)
        {
            int index = isExisting(id);
            List<Item> cart = (List<Item>)Session["cart"];
            cart.RemoveAt(index);
            Session["cart"] = cart;
            return View("Caddie");
        }
        public ActionResult AjouterCaddie(int id)
        {
            if(Session["cart"]==null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item(Iprod.findProduit(id), 1));
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExisting(id);
                if (index == -1)
                    cart.Add(new Item(Iprod.findProduit(id), 1));
                else
                    cart[index].Quantity++;
                Session["cart"] = cart;
            
            }
            return View("Caddie");
        }

        public ActionResult Update(FormCollection fc)
        {
            string[] quantities = fc.GetValues("qute");
            List<Item> cart = (List<Item>)Session["cart"];
            for(int i=0;i < cart.Count;i++)
                cart[i].Quantity = Convert.ToInt32(quantities[i]);
            Session["cart"] = cart;
            return View("Caddie");
        }


        public ActionResult ValiderPanier()
        {
            List<Item> cart = (List<Item>)Session["cart"];
            UserAccount user = (UserAccount)Session["user"];
            //ajouter la commande en BDD
            Commande c = new Commande();
            c.DateCommande = DateTime.Now;
            //c.UserAccount = user;
            c.Statut = "Valide";
            c.UserAccountId = user.UserAccountId;
            Iuser.EnregistrerCommande(c);

            //ajouter des Lignes de Commande en BDD
            foreach(Item item in cart)
            {
                LigneCommande lc = new LigneCommande();
                lc.CommandeId = c.CommandeId;
                lc.quantite = item.Quantity;
                lc.prix = item.Pr.prix;
                lc.ProduitId = item.Pr.ProduitId;
                Iuser.SauvegarderLigneCommande(lc);
            }
            //vider la session Caddie
            Session.Remove("cart");
            return View("Thanks");
        }

        public ActionResult CheckoutCheque()
        {

            List<Item> cart = (List<Item>)Session["cart"];
            UserAccount user = (UserAccount)Session["user"];
            //ajouter la commande en BDD
            Commande c = new Commande();
            c.DateCommande = DateTime.Now;
            //c.UserAccount = user;
            c.Statut = "En Cours";
            c.UserAccountId = user.UserAccountId;
            Iuser.EnregistrerCommande(c);

            //ajouter des Lignes de Commande en BDD
            foreach (Item item in cart)
            {
                LigneCommande lc = new LigneCommande();
                lc.CommandeId = c.CommandeId;
                lc.quantite = item.Quantity;
                lc.prix = item.Pr.prix;
                lc.ProduitId = item.Pr.ProduitId;
                Iuser.SauvegarderLigneCommande(lc);
            }
            //vider la session Caddie
            Session.Remove("cart");
            return View("Thanks");

        }
        public ActionResult MesCommandes(int id)
        {
            return View(Iuser.ListerMesCommandes(id));
        }

        public ActionResult MesConsultations()
        {
            return View();
        }
        public ActionResult Detail(int id)
        {
            UserAccount user = (UserAccount)Session["user"];
            Consulter c = new Consulter();
            c.DateConsultation = DateTime.Now;
            c.UserAccountId = user.UserAccountId;
            c.ProduitId = id;
            Iuser.ProduitsVisites(c);

            var res = Iprod.findProduit(id);
            return View(res);
        }

        public ActionResult CheckoutPaypal()
        {
            // création de l'url de connexion à paypal
            string returnURL = "";
            returnURL += "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_cart&upload=1&business=services.huios-pro@gmail.com";
            List<Item> cart = (List<Item>)Session["cart"];
            int i = 0;
            foreach (Item item in cart)
            {
                i++;
                returnURL += "&item_name_"+i+"=" + item.Pr.NomProduit;
                returnURL += "&item_number_" + i + "=" + i.ToString();
                returnURL += "&quantity_" + i + "=" + item.Quantity;
                returnURL += "&amount_" + i + "=" + item.Pr.prix;
            }
            //devise par défaut
            returnURL += "&currency=EUR";
            //URL de retour à la page précédente
            returnURL += "&return=http://localhost:58327/UserAccount/Commander";
            //URL en cas d'annulation de la transaction
            returnURL += "&cancel_return=http://localhost:58327/UserAccount/Commander";

            //vider la session Caddie
            Session.Remove("cart");

            return Redirect(returnURL);
        }
    }
}

MiniFilRouge/Views/UserAccount/Caddie.cshtml
@{
    ViewBag.Title = "Caddie";
}
@using MiniFilRouge.Controllers

<h4>Bonjour @Session["Username"] (@Session["UserId"])</h4>
@using (Html.BeginForm("Update", "UserAccount"))
{ 
<table class="table table-striped">
    <tr>
        <th>OPTION</th>
        <th>ID</th>
        <th>NOM</th>
        <th>PRIX</th>
        <th>QUANTITE <input type="submit" value="Update"/></th>
        <th>SOUS TOTAL</th>
    </tr>
    @{ 
        decimal s = 0;
        int index = 1;
    }
    @foreach(Item item in (List<Item>)Session["cart"])
    {
        s = s + item.Pr.prix * item.Quantity;
        <tr>
            <td>@Html.ActionLink("Supprimer","Delete", "UserAccount",
               new { id=item.Pr.ProduitId},null)</td>
            <td>@item.Pr.ProduitId</td>
            <td>@item.Pr.NomProduit</td>
            <td>@item.Pr.prix</td>
            <td><input type="text" value="@item.Quantity" name="qute" class="qute"/></td>
            <td>
                @(item.Pr.prix * item.Quantity)
                @{ index++;}
            </td>
        </tr>
    }
    <tr>
        <td align="right" colspan="5">Total</td>
        <td>@s</td>
    </tr>
</table>
}
@Html.ActionLink("Continuer mes achats", "Commander", "UserAccount")
<p align="right">
    @Html.ActionLink("Valider le panier", "ValiderPanier", "UserAccount")
</p><br/>
<p align="right">
    @Html.ActionLink("Checkout Paypal", "CheckoutPaypal", "UserAccount")
</p><br />
<p align="right">
    @Html.ActionLink("Checkout Chèque", "CheckoutCheque", "UserAccount")
</p><br />

MiniFilRouge/Views/UserAccount/Commander.cshtml
@model IEnumerable<MiniFilRouge.Metier.Produit>
@{
    ViewBag.Title = "Commander";
}
<html>
<head>

</head>
<body>
    <br />
    <h3>Liste des produits</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.ProduitId)</th>
                <th>@Html.DisplayNameFor(model => model.NomProduit)</th>
                <th>@Html.DisplayNameFor(model => model.prix)</th>
                <th>Détail du produit</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var p in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => p.ProduitId)</td>
                    <td>@Html.DisplayFor(modelItem => p.NomProduit)</td>
                    <td>@Html.DisplayFor(modelItem => p.prix)</td>
                    <td>@Html.ActionLink("Détails", "Detail" 
                                     ,new { id = p.ProduitId }, null)</td>
                    <td>@Html.ActionLink("Order Now", "AjouterCaddie",
                       "UserAccount",new { id=p.ProduitId},null)</td>
                   
                </tr>

            }

        </tbody>
    </table>
</body>
</html>

MiniFilRouge/Views/UserAccount/Detail.cshtml
@model MiniFilRouge.Metier.Produit
@{
    ViewBag.Title = "Detail";
}

<h2>Detail Produit</h2>

<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProduitId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomProduit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stock)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProduitId }) |
    @Html.ActionLink("Back to List", "Commander")
</p>

MiniFilRouge/Views/UserAccount/Index.cshtml
@model IEnumerable<MiniFilRouge.Metier.UserAccount>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
    </tr>
}

</table>

MiniFilRouge/Views/UserAccount/LoggedIn.cshtml
@{
    ViewBag.Title = "LoggedIn";
}
@if(Session["UserId"]!=null)
{
    <h4>Hello @Session["Username"].ToString()</h4>
}
<div>
    <span>@Html.ActionLink("Commander", "Commander")</span>
    <span>@Html.ActionLink("Mes Commandes", "MesCommandes", new { id = Session["userId"] })</span>
    <br/>
    <br/>
    <br/>
</div>
<div>
    @Html.ActionLink("Se déconnecter", "Logout")<br />
</div>

MiniFilRouge/Views/UserAccount/Login.cshtml
@model MiniFilRouge.Metier.UserAccount

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserAccount</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MiniFilRouge/Views/UserAccount/MesCommandes.cshtml
@model IEnumerable<MiniFilRouge.Models.MesCommandes>
@{
    ViewBag.Title = "MesCommandes";
}

<h2>MesCommandes</h2>
<h2>Produits</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.PrenomClient)</th>
            <th>@Html.DisplayNameFor(model => model.NomClient)</th>
            <th>@Html.DisplayNameFor(model => model.NomProduit)</th>
            <th>@Html.DisplayNameFor(model => model.Quantite)</th>
            <th>@Html.DisplayNameFor(model => model.PrixTotal)</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var p in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => p.PrenomClient)</td>
                <td>@Html.DisplayFor(modelItem => p.NomClient)</td>
                <td>@Html.DisplayFor(modelItem => p.NomProduit)</td>
                <td>@Html.DisplayFor(modelItem => p.Quantite)</td>
                <td>@Html.DisplayFor(modelItem => p.PrixTotal)</td>
            </tr>

        }

    </tbody>
</table>

MiniFilRouge/Views/UserAccount/Register.cshtml
@model MiniFilRouge.Metier.UserAccount

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserAccount</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @if (ViewBag.Message != null)
        {
            <div class="form-group">
                <div class="col-md-10">@ViewBag.Message</div>
            </div>
        }
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Register" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MiniFilRouge/Views/UserAccount/Thanks.cshtml
@{
    ViewBag.Title = "Thanks";
}
 
<h2>Thanks</h2>

MiniFilRouge/Views/UserAccount/ValiderPanier.cshtml
@{
    ViewBag.Title = "ValiderPanier";
}

<h2>ValiderPanier</h2>