MiniFilRouge/Controllers/MagasinController.cs
using MiniFilRouge.Metier;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniFilRouge.Controllers
{
    public class MagasinController : Controller
    {
        public IMagasin Imag = new MagasinImpl();
        public IProduit Iprod = new ProduitImpl();
        // GET: Magasin
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Magasin m)
        {
            Imag.AjouterMagasin(m);
            return View();
        }
        public ActionResult MagasinProduit()
        {
            ViewBag.MagasinId = new SelectList(Imag.findAllMagasins(), "MagasinId", "NomMagasin");
            ViewBag.ProduitId = new SelectList(Iprod.findAllProduits(), "ProduitId", "NomProduit");
            return View();
        }
        [HttpPost]
        public ActionResult MagasinProduit(ProduitMagasin pm)
        {
            Imag.AddProduitMagasin(pm.MagasinId,pm.ProduitId,pm.quantite);
            ViewBag.MagasinId = new SelectList(Imag.findAllMagasins(), "MagasinId", "NomMagasin");
            ViewBag.ProduitId = new SelectList(Iprod.findAllProduits(), "ProduitId", "NomProduit");
            return View();
        }

        public ActionResult ListMagasinProduit()
        {
            return View(Imag.findAllMagasinsProduits());
        }
    }
}

MiniFilRouge/Views/Magasin/Index.cshtml
@model IEnumerable<MiniFilRouge.Metier.Magasin>
@{
    ViewBag.Title = "Index";
}
<html>
    <head>

    </head>
    <body>
        <div>
            <div>
                @using (Html.BeginForm("Index", "Magasin", FormMethod.Post))
            {
                    <span>@Html.DisplayNameFor(model=>model.NomMagasin):</span>@Html.TextBox("NomMagasin")<br />
                    <button type="submit" class="btn-primary text-center">Ajouter</button>
                }
            </div>
        </div>
    </body>
</html>

MiniFilRouge/Views/Magasin/ListMagasinProduit.cshtml
@model IEnumerable<MiniFilRouge.Models.ProduitMagasinModel>
@{
    ViewBag.Title = "ListMagasinProduit";
}

<h2>ListMagasinProduit</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.NomProduit)</th>
            <th>@Html.DisplayNameFor(model => model.NomMagasin)</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var p in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => p.NomProduit)</td>
                <td>@Html.DisplayFor(modelItem => p.NomMagasin)</td>
            </tr>

        }

    </tbody>
</table>

MiniFilRouge/Views/Magasin/MagasinProduit.cshtml
@model IEnumerable<MiniFilRouge.Metier.ProduitMagasin>
@{
    ViewBag.Title = "MagasinProduit";
}

<h2>MagasinProduit</h2>

@using (Html.BeginForm("MagasinProduit", "Magasin", FormMethod.Post))
            {
                <span>@Html.DisplayNameFor(model => model.quantite) :</span>@Html.TextBox("quantite")<br />
                <span>@Html.DisplayNameFor(model => model.Magasin) :</span>@Html.DropDownList("MagasinId", null, htmlAttributes: new { @class = "form-control" })<br />
                <span>@Html.DisplayNameFor(model => model.Produit) :</span>@Html.DropDownList("ProduitId", null, htmlAttributes: new { @class = "form-control" })<br />
                <button type="submit" class="btn-primary text-center">Ajouter</button>
            }