MiniFilRouge/Controllers/ProduitController.cs
using MiniFilRouge.Metier;
using MiniFilRouge.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniFilRouge.Controllers
{
    public class ProduitController : Controller
    {
        public IProduit Iproduit = new ProduitImpl();
        public ICategorie Icat = new CategorieImpl();
        // GET: Produit
        public ActionResult Index()
        {
            ICollection<Produit> res = Iproduit.findAllProduits();
            ViewBag.CategorieId = new SelectList(Icat.findAllCategories(), "CategorieId", "Nom");
            return View(res);
            //return View();
        }
        [HttpPost]
        public ActionResult Index(Produit p)
        {
            ICollection<Produit> res = Iproduit.findAllProduits();
            if (ModelState.IsValid)
            { 
            Iproduit.AddProduit(p);
            ViewBag.CategorieId = new SelectList(Icat.findAllCategories(), "CategorieId", "Nom");
            }
            else {
                ViewBag.CategorieId = new SelectList(Icat.findAllCategories(), "CategorieId", "Nom");
            }
            return View(res);
        }
        public ActionResult Edit(int id)
        {
            Produit produit = Iproduit.findProduit(id);
            ViewBag.CategorieId = new SelectList(Icat.findAllCategories(), "CategorieId", "Nom");
            return View(produit);
        }
        [HttpPost]
        public ActionResult Edit(Produit produit)
        {
            if (ModelState.IsValid)
            {
                Iproduit.MajProduit(produit);
                return RedirectToAction("Index");
            }
            else
            {
                return View(produit);
            }
        }
        public ActionResult Delete(int id)
        {
            Iproduit.DeleteProduit(id);
            return RedirectToAction("Index");
        }

        public ActionResult Produits(ProduitCatModel pm)
        {
            ICollection<ProduitCatModel> res = Iproduit.findAllProduitsAndCat();
            return View(res);
        }
    }
}

MiniFilRouge/Views/Produit/Edit.cshtml
@model MiniFilRouge.Metier.Produit
    @{
        ViewBag.Title = "Edit";
    }
    <html>
    <head>

    </head>
    <body>
@using (Html.BeginForm("Edit", "Produit", FormMethod.Post))
{
    @Html.HiddenFor(model => model.ProduitId)
    <span>Nom :</span>@Html.EditorFor(model => model.NomProduit)<br />
    <span>Prix :</span>@Html.EditorFor(model => model.prix)<br />
    <span>Stock :</span>@Html.EditorFor(model => model.stock)<br />
    <span>Categorie :</span>@Html.DropDownList("CategorieId")<br /><br />
    <button type="submit" class="btn-primary text-center">MAJ</button>
}
    </body>
</html>

MiniFilRouge/Views/Produit/Index.cshtml
@model IEnumerable<MiniFilRouge.Metier.Produit>
@{
    ViewBag.Title = "Index";
}
<html>
    <head>

    </head>
    <body>
        <br />
        <div class="form-horizontal">
            @using (Html.BeginForm("Index", "Produit", FormMethod.Post))
            {@* Marche pas car on utilise pas le bon modèle*@
                //@Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <span>@Html.DisplayNameFor(model => model.NomProduit) :</span>
                 @Html.TextBox("NomProduit")
                @* Marche pas car on utilise pas le bon modèle*@
               // @Html.ValidationMessageFor(model => model., "", new { @class = "text-danger" })<br />
                <span>@Html.DisplayNameFor(model => model.prix) :</span>@Html.TextBox("prix")<br />
                <span>@Html.DisplayNameFor(model => model.stock) :</span>@Html.TextBox("stock")<br />
                <span>@Html.DisplayNameFor(model => model.Categorie) :</span>
                @Html.DropDownList("CategorieId", null, htmlAttributes: new { @class = "form-control" })<br />
              
                <button type="submit" class="btn-primary text-center">Ajouter</button>
            }
        </div>
        <h3>Liste des produits</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.ProduitId)</th>
                    <th>@Html.DisplayNameFor(model => model.NomProduit)</th>
                    <th>@Html.DisplayNameFor(model => model.prix)</th>
                    <th>@Html.DisplayNameFor(model => model.stock)</th>
                    <th>@Html.DisplayNameFor(model => model.Categorie)</th>
                    
                </tr>
            </thead>
            <tbody>

                @foreach (var p in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => p.ProduitId)</td>
                        <td>@Html.DisplayFor(modelItem => p.NomProduit)</td>
                        <td>@Html.DisplayFor(modelItem => p.prix)</td>
                        <td>@Html.DisplayFor(modelItem => p.stock)</td>
                        <td>@Html.DisplayFor(modelItem => p.CategorieId)</td>
          
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = p.ProduitId })
                        </td>
                        <td>
                            @Html.ActionLink("Delete", "Delete", new { id = p.ProduitId })
                        </td>
                    </tr>

                }

            </tbody>
        </table>
    </body>
</html>

MiniFilRouge/Views/Produit/Produits.cshtml
@model IEnumerable<MiniFilRouge.Models.ProduitCatModel>
@{
    ViewBag.Title = "Produits";
}

<h2>Produits</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.ProduitId)</th>
            <th>@Html.DisplayNameFor(model => model.NomProduit)</th>
            <th>@Html.DisplayNameFor(model => model.prix)</th>
            <th>@Html.DisplayNameFor(model => model.stock)</th>
            <th>@Html.DisplayNameFor(model => model.nomCat)</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var p in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => p.ProduitId)</td>
                <td>@Html.DisplayFor(modelItem => p.NomProduit)</td>
                <td>@Html.DisplayFor(modelItem => p.prix)</td>
                <td>@Html.DisplayFor(modelItem => p.stock)</td>
                <td>@Html.DisplayFor(modelItem => p.nomCat)</td>
            </tr>

        }

    </tbody>
</table>