MiniFilRouge/Controllers/CategorieController.cs
using MiniFilRouge.Metier;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniFilRouge.Controllers
{
    public class CategorieController : Controller
    {
        public ICategorie Icat = new CategorieImpl();
        // GET: Categorie
        public ActionResult Index()
        {
            ICollection<Categorie> res = Icat.findAllCategories();
            return View(res);
        }

        public ActionResult Chercher()
        {
            return View();
        }
        public ActionResult Categories()
        {
            return View();
        }
        public ActionResult AjouterCategorie()
        {
            ICollection<Categorie> res = Icat.findAllCategories();
            return View(res);
        }
        [HttpPost]
        public ActionResult AjouterCategorie(Categorie c)
        {
            Icat.AddCategorie(c);
            ICollection<Categorie> res = Icat.findAllCategories();
            return View(res);
        }
        /* suppression d'une catégorie*/
        public ActionResult Delete(int id)
        {
            Icat.DeleteCategorie(id);
            return RedirectToAction("AjouterCategorie");
        }
        // GET: Categorie/Edit/5
        public ActionResult Edit(int id)
        {
            Categorie categorie = Icat.findCategorie(id);
            return View(categorie);
        }
        [HttpPost]
        public ActionResult Edit([Bind(Include = "CategorieId,Nom")]Categorie categorie)
        {
            if (ModelState.IsValid)
            {
                Icat.MajCategorie(categorie);
                return RedirectToAction("AjouterCategorie");
            }
            else
            {
                return View(categorie);
            }
        }
    }
}

MiniFilRouge/Views/Categorie/AjouterCategorie.cshtml
@model IEnumerable<MiniFilRouge.Metier.Categorie>
@{
    ViewBag.Title = "AjouterCategorie";
}
<html>
    <head>

    </head>
    <body>
        <br/>
        <div>
            @using (Html.BeginForm("AjouterCategorie", "Categorie", FormMethod.Post))
            {
                <span>Entrer nom Catégorie:</span>@Html.TextBox("Nom")<br/>
                <button type="submit" class="btn-primary text-center">Ajouter</button>
            }
        </div>


        <table class="table table-striped">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.CategorieId)</th>
                    <th>@Html.DisplayNameFor(model => model.Nom)</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var p in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => p.CategorieId)</td>
                        <td>@Html.DisplayFor(modelItem => p.Nom)</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = p.CategorieId })
                        </td>
                        <td>
                            @Html.ActionLink("Delete", "Delete", new { id = p.CategorieId })
                        </td>
                    </tr>

                }

            </tbody>
        </table>

    </body>
</html>

MiniFilRouge/Views/Categorie/Categories.cshtml
@{
    ViewBag.Title = "Categories";
}
<h2>Categories</h2>
<div class="container spacer">
    <form method="post" action="/Produit/Chercher">
        <div class="form-group">
            <label>Mot Clé:</label>
            <input type="text" name="motCle" value="@Html.ViewBag.motCle"/>
            <button type="submit">Chercher</button>
            @Html.ValidationMessage("motCle",new { @class="text-danger"})
        </div>
    </form>
</div>

MiniFilRouge/Views/Categorie/Edit.cshtml
@model MiniFilRouge.Metier.Categorie
@{
    ViewBag.Title = "Edit";
}
<html>
    <head>

    </head> 
    <body>
  
@using (Html.BeginForm("Edit", "Categorie", FormMethod.Post))
{    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CategorieId)
    <span>Nom :</span>@Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
<br />
    <button type="submit" class="btn-primary text-center">MAJ</button>
}
    </body>
</html>

MiniFilRouge/Views/Categorie/Index.cshtml
@model IEnumerable<MiniFilRouge.Metier.Categorie>
@{
    ViewBag.Title = "Liste des Categories";
}
<h2>Liste des Catégories</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model=>model.CategorieId)</th>
            <th>@Html.DisplayNameFor(model => model.Nom)</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var p in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem=>p.CategorieId)</td>
                <td>@Html.DisplayFor(modelItem => p.Nom)</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = p.CategorieId })
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = p.CategorieId })
                </td>
            </tr>

        }

    </tbody>
</table>